modLoader="javafml"

loaderVersion="[40,)"

# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

issueTrackerURL="https://github.com/anviaan/SimpleMango/issues"
[[mods]]

modId="bedrockplus"

version="1.2.1"

displayName="Bedrock Plus Mod"

updateJSONURL="https://anvian-page.netlify.app/forge/bedrockPlus.json"

displayURL="https://www.curseforge.com/minecraft/mc-mods/bedrock-pus"

authors="anvian"

description="Adds a new variant of bedrock, which can be combined with netherite armor."

[[dependencies.bedrockplus]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bedrockplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
